<?php

return [
    '1' => [
        'id' => '1',
        'parent_id' => '0',
        'name' => 'Main page',
        'url' => '',
        'active' => '1',
        'content' => '',
    ],
    '2' => [
        'id' => '2',
        'parent_id' => '1',
        'name' => 'About',
        'url' => '/about',
        'active' => '1',
        'content' => '',
    ],
    '3' => [
        'id' => '3',
        'parent_id' => '1',
        'name' => 'Contacts',
        'url' => '/contacts',
        'active' => '1',
        'content' => '',
    ],
    '4' => [
        'id' => '4',
        'parent_id' => '1',
        'name' => 'Portfolio',
        'url' => '/portfolio',
        'active' => '1',
        'content' => '',
    ],
    '5' => [
        'id' => '5',
        'parent_id' => '1',
        'name' => 'Test',
        'url' => '/test',
        'active' => '0',
        'content' => '',
    ],
    '6' => [
        'id' => '6',
        'parent_id' => '1',
        'name' => 'News',
        'url' => '/news',
        'active' => '1',
        'content' => '',
    ],
    '7' => [
        'id' => '7',
        'parent_id' => '6',
        'name' => 'It is the first news',
        'url' => '/news/1',
        'active' => '0',
        'content' => 'Truth only',
    ],
    '8' => [
        'id' => '8',
        'parent_id' => '6',
        'name' => 'The second',
        'url' => '/news/second',
        'active' => '1',
        'content' => 'Hello! Do you want some breaking news?',
    ],
    '9' => [
        'id' => '9',
        'parent_id' => '6',
        'name' => '3',
        'url' => '/news/3-rd',
        'active' => '1',
        'content' => 'Just a text.',
    ],
];
